flowchart LR
  ROOT["Proeveresultat"]
  ROOT --> H["Haendelse"]
  ROOT --> R["Resultat"]
  ROOT -.-> U["Us_procedure"]
  ROOT -.-> AL["Anatomisk_Lokalisation"]
  ROOT -.-> M["Morfologi"]
  ROOT -.-> TP["Proeveresultat_til_procedure"]
  ROOT -.-> REQ["Proeveresultat_rekvireret_af"]
  REQ -.-> RB["Rekvirerende_Behandler"]
  REQ --> RE["Rekvirerende_Enhed"]
  ROOT --> PROD["Proeveresultat_produceret_af"]
  PROD -.-> PB["Producerende_Behandler"]
  PROD --> PE["Producerende_Enhed"]
