flowchart LR
  ROOT["Medicingivning"]
  ROOT --> H["Haendelse"]
  ROOT --> T["Type"]
  ROOT --> PR["Praeparat"]
  ROOT -.-> I["Indikation"]
  ROOT -.-> AA["AfslutningsAarsag"]
  ROOT --> ATC["ATC_Kode"]
  ROOT --> AM["Administrationsmaade"]
  ROOT -.-> F["Form"]
  ROOT --> G["Medicin_givet_af"]
  G -.-> PB["Producerende_Behandler"]
  G --> PE["Producerende_Enhed"]
  ROOT -.-> O["Medicingivning_ordineret_af"]
  O -.-> OB["Ordinerende_Behandler"]
  O --> OE["Ordinerende_Enhed"]
  ROOT --> A["Medicingivning_afsluttet_af"]
  A --> AE["Afsluttende_Enhed"]
  A -.-> AB["Afsluttende_Behandler"]
  ROOT -.-> FRS["Medicingivning_foraarsaget_af"]
