flowchart LR
  ROOT["Rekvisition"]
  ROOT --> H["Haendelse"]
  ROOT -.-> PK["Procedure_kode"]
  ROOT -.-> I["Indikation"]
  ROOT -.-> P["Prioritet"]
  ROOT -.-> A["AfslutningsAarsag"]
  ROOT -.-> U["Rekvisition_udloest_af"]
  ROOT --> R["Rekvisition_rekvireret_af"]
  R -.-> RB["Rekvirerende_Behandler"]
  R --> RE["Rekvirerende_Enhed"]
  ROOT --> PP["Rekvisition_planlagt_produceret_af"]
  PP -.-> PB["Producerende_Behandler"]
  PP --> PE["Producerende_Enhed"]
  ROOT -.-> F["Rekvisition_faktisk_afsluttet_af"]
  F -.-> AB["Afsluttende_Behandler"]
  F --> AE["Afsluttende_Enhed"]
