flowchart LR
  ROOT["Kontaktperiode"]
  ROOT --> H["Haendelse"]
  ROOT --> FS["ForloebsStatus"]
  ROOT -.-> I["Indikation"]
  ROOT -.-> P["Prioritet"]
  ROOT -.-> A["AfslutningsAarsag"]
  ROOT --> L["Laegelig_Ansvarlig_for_kontaktperiode"]
  L -.-> LB["Laegelig_ansvarlig_behandler"]
  L --> LE["Laegelig_kontaktansvarlig_Enhed"]
  ROOT -.-> K["Kontaktperiode_afsluttet_af"]
  K -.-> AB["Afsluttende_Behandler"]
  K --> AE["Afsluttende_Enhed"]
  ROOT -.-> R["Rekv_enhed_til_kontaktperiode"]
  R -.-> RB["Rekvirerende_Behandler"]
  R --> RE["Rekvirerende_Enhed"]
  ROOT -.-> HEN["Henvisning"]
  ROOT -.-> KG["Kontaktgrundlag"]
