<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.medcom.dk/SUP_30" xmlns="http://www.medcom.dk/SUP_30" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:include schemaLocation="SUPTyper.xsd"/>
	<xsd:include schemaLocation="SUPKlassifikation.xsd"/>
	<xsd:include schemaLocation="SUPOrganisation.xsd"/>
	<xsd:include schemaLocation="SUPBehandlere.xsd"/>
	<xsd:include schemaLocation="SUPFaellesAttributter.xsd"/>
	<xsd:include schemaLocation="SUPHaendelse.xsd"/>
	<!-- ====================== Pakke: Kontaktperiode =========================-->
	<xsd:element name="Kontaktperiode">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Haendelse"/>
				<xsd:element ref="ForloebsStatus"/>
				<xsd:element ref="Indikation" minOccurs="0"/>
				<xsd:element ref="Prioritet" minOccurs="0"/>
				<xsd:element ref="AfslutningsAarsag" minOccurs="0"/>
				<xsd:element ref="Laegelig_Ansvarlig_for_kontaktperiode"/>
				<xsd:element ref="Kontaktperiode_afsluttet_af" minOccurs="0"/>
				<xsd:element ref="Rekv_enhed_til_kontaktperiode" minOccurs="0"/>
				<xsd:element ref="Henvisning" minOccurs="0"/>
				<xsd:element ref="Kontaktgrundlag" minOccurs="0"/>
			</xsd:sequence>
			<xsd:attribute name="StartTidspunkt" type="SUPdateTime" use="required"/>
			<xsd:attribute name="Afslutningstidspunkt" type="SUPdateTime" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Kontaktperiode_afsluttet_af">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Afsluttende_Behandler" minOccurs="0"/>
				<xsd:element ref="Afsluttende_Enhed"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Laegelig_Ansvarlig_for_kontaktperiode">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Laegelig_ansvarlig_behandler" minOccurs="0"/>
				<xsd:element ref="Laegelig_kontaktansvarlig_Enhed"/>
			</xsd:sequence>
			<xsd:attribute name="Stamsted" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Rekv_enhed_til_kontaktperiode">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="Rekvirerende_Behandler" minOccurs="0"/>
				<xsd:element ref="Rekvirerende_Enhed"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="ForloebsStatus">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="KodetVaerdi"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Henvisning">
		<xsd:complexType>
			<xsd:attribute name="Rekvisition_Identifikation" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="Kontaktgrundlag">
		<xsd:complexType>
			<xsd:attribute name="Ordination_Identifikation" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>
