flowchart TB
    H["Hændelser"]
    E0["Medicinordination"]
    E1["Medicingivning"]
    E2["Notat"]
    E3["Prøveresultat"]
    E4["Observation/fund"]
    E5["Diagnose"]
    E6["Administrativ karakteristikum"]
    E7["Rekvisition"]
    E8["Kontaktperiode"]
    E9["Udført procedure"]
    E10["Ordination"]
    E11["Planlagt procedure"]
    E12["Booking af procedure"]
    E13["Anamnestisk oplysning"]
    E14["Effekt af behandling"]
    E15["Komplikation/bivirkning"]
    E16["Problem"]
    E17["Mål"]
    H -->|"type"| E0
    H -->|"type"| E1
    H -->|"type"| E2
    H -->|"type"| E3
    H -->|"type"| E4
    H -->|"type"| E5
    H -->|"type"| E6
    H -->|"type"| E7
    H -->|"type"| E8
    H -->|"type"| E9
    H -->|"type"| E10
    H -->|"type"| E11
    H -->|"type"| E12
    H -->|"type"| E13
    H -->|"type"| E14
    H -->|"type"| E15
    H -->|"type"| E16
    H -->|"type"| E17
