flowchart TD
  A[AfdelingsBeskrivelse<br/>Version = 2.0] --> B[Organisatorisk_Enhed]
  A --> C[Beskrivelse]
  A --> D[HaendelsesBeskrivelse<br/>1..*]
  B --> B1[Kode 0..1]
  B --> B2[Institution_tekst 0..1]
  B --> B3[Afdeling_tekst 0..1]
  D --> E[Haendelse]
  D --> F[Beskrivelse]
  E --> G{HaendelsesType}
  G --> G1[Kontaktperiode]
  G --> G2[Medicinordination]
  G --> G3[Medicingivning]
  G --> G4[Notat]
  G --> G5[Booking_af_procedure]
  G --> G6[Ordination]
  G --> G7[Planlagt_procedure]
  G --> G8[Rekvisition]
  G --> G9[Udfoert_procedure]
  G --> G10[Anamnestisk_oplysning]
  G --> G11[Observation_fund]
  G --> G12[Proeveresultat]
  G --> G13[Diagnose]
  G --> G14[Effekt_af_behandling]
  G --> G15[Komplikation_bivirkning]
  G --> G16[Maal]
  G --> G17[Problem]
