spring.application.name=ejournal-sdk-fhir-demo
server.address=127.0.0.1
server.port=8081
sdk.base-url=${SDK_BASE_URL:http://localhost:8080}
sdk.timeout-seconds=${SDK_TIMEOUT_SECONDS:10}
spring.web.resources.cache.cachecontrol.no-store=true
server.error.include-message=never
server.error.include-stacktrace=never
