<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.medcom.dk/SUP_30" xmlns="http://www.medcom.dk/SUP_30" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:annotation>
		<xsd:documentation>SUP II version 3.0 XML schema for "Meddelelser-Service".</xsd:documentation>
	</xsd:annotation>
	<xsd:include schemaLocation="SUPTyper.xsd"/>
	<xsd:annotation>
		<xsd:documentation>
		Giver for et cpr-nummer liste over alle meddelelser vedrørende udtræk til SUB databasen.
     		</xsd:documentation>
	</xsd:annotation>
	<xsd:complexType name="MeddelelseType">
		<xsd:sequence>
			<xsd:element ref="Dato"/>
			<xsd:element ref="Returtekst"/>
			<xsd:element ref="Returkode"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="Meddelelsesliste">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Person" type="PersonType"/>
				<xsd:element name="Meddelelse" type="MeddelelseType" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="PersonType">
		<xsd:sequence>
			<xsd:element ref="CPRnummer"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="CPRnummer" type="xsd:string"/>
	<xsd:element name="Dato" type="SUPdateTime"/>
	<xsd:element name="Returtekst" type="xsd:string"/>
	<xsd:element name="Returkode" type="xsd:nonNegativeInteger"/>
</xsd:schema>
