flowchart TB
    H["Hændelse"]
    E0["Medicinordination"]
    E1["Medicingivning"]
    E2["Notat"]
    E3["Prøveresultat"]
    E4["Observation/fund"]
    E5["Diagnose"]
    E6["Administrativ karakteristikum"]
    E7["Rekvisition"]
    E8["Kontaktperiode"]
    E9["Udført procedure"]
    E10["Ordination"]
    E11["Planlagt procedure"]
    E12["Booking af procedure"]
    E13["Anamnestisk oplysning"]
    E14["Effekt af behandling"]
    E15["Komplikation/bivirkning"]
    E16["Problem"]
    E17["Mål"]
    H -->|"specialisering"| E0
    H -->|"specialisering"| E1
    H -->|"specialisering"| E2
    H -->|"specialisering"| E3
    H -->|"specialisering"| E4
    H -->|"specialisering"| E5
    H -->|"specialisering"| E6
    H -->|"specialisering"| E7
    H -->|"specialisering"| E8
    H -->|"specialisering"| E9
    H -->|"specialisering"| E10
    H -->|"specialisering"| E11
    H -->|"specialisering"| E12
    H -->|"specialisering"| E13
    H -->|"specialisering"| E14
    H -->|"specialisering"| E15
    H -->|"specialisering"| E16
    H -->|"specialisering"| E17
