flowchart LR
  K[Kontaktperiode] --> H[Haendelse]
  K --> F[ForloebsStatus]
  K -. optional .-> I[Indikation]
  K -. optional .-> P[Prioritet]
  K -. optional .-> A[AfslutningsAarsag]
  K --> L[Laegelig_Ansvarlig_for_kontaktperiode]
  L -. optional .-> LB[Laegelig_ansvarlig_behandler]
  L --> LE[Laegelig_kontaktansvarlig_Enhed]
  K -. optional .-> AF[Kontaktperiode_afsluttet_af]
  AF -. optional .-> AB[Afsluttende_Behandler]
  AF --> AE[Afsluttende_Enhed]
  K -. optional .-> R[Rekv_enhed_til_kontaktperiode]
  R -. optional .-> RB[Rekvirerende_Behandler]
  R --> RE[Rekvirerende_Enhed]
  K -. optional .-> HV[Henvisning]
  K -. optional .-> KG[Kontaktgrundlag]
