flowchart LR
  R[Rekvisition] --> H[Haendelse]
  R --> PK[Procedure_kode]
  R -. optional .-> I[Indikation]
  R -. optional .-> P[Prioritet]
  R -. optional .-> A[AfslutningsAarsag]
  R -. optional .-> U[Rekvisition_udloest_af]
  R --> RR[Rekvisition_rekvireret_af]
  RR -. optional .-> RB[Rekvirerende_Behandler]
  RR --> RE[Rekvirerende_Enhed]
  R --> PP[Rekvisition_planlagt_produceret_af]
  PP -. optional .-> PB[Producerende_Behandler]
  PP --> PE[Producerende_Enhed]
  R -. optional .-> AF[Rekvisition_faktisk_afsluttet_af]
  AF -. optional .-> AB[Afsluttende_Behandler]
  AF --> AE[Afsluttende_Enhed]
