flowchart LR
  A[Aflever_patientdata] -->|0..*| P[Person]
  P -->|0..*| PF[Patientforloeb]
  P -->|0..*| C[CaveOplysninger]
  PF --> OA[OprindeligAnsvarligEnhed]
  PF --> CH{{choice 0..*}}
  CH --> AK[Administrativ_karakteristikum]
  CH --> KP[Kontaktperiode]
  CH --> MO[Medicinordination]
  CH --> MG[Medicingivning]
  CH --> N[Notat]
  CH --> B[Booking_af_procedure]
  CH --> O[Ordination]
  CH --> PP[Planlagt_procedure]
  CH --> R[Rekvisition]
  CH --> UP[Udfoert_procedure]
  CH --> AO[Anamnestisk_oplysning]
  CH --> OF[Observation_fund]
  CH --> PR[Proeveresultat]
  CH --> D[Diagnose]
  CH --> EB[Effekt_af_behandling]
  CH --> KB[Komplikation_bivirkning]
  CH --> M[Maal]
  CH --> PB[Problem]
