flowchart LR
  M[Medicingivning] --> H[Haendelse]
  M --> T[Type]
  M --> P[Praeparat]
  M -. optional .-> I[Indikation]
  M -. optional .-> A[AfslutningsAarsag]
  M -. optional .-> ATC[ATC_Kode]
  M -. optional .-> ADM[Administrationsmaade]
  M -. optional .-> F[Form]
  M --> G[Medicin_givet_af]
  G -. optional .-> PB[Producerende_Behandler]
  G --> PE[Producerende_Enhed]
  M -. optional .-> O[Medicingivning_ordineret_af]
  O -. optional .-> OB[Ordinerende_Behandler]
  O --> OE[Ordinerende_Enhed]
  M --> AF[Medicingivning_afsluttet_af]
  AF --> AE[Afsluttende_Enhed]
  AF -. optional .-> AB[Afsluttende_Behandler]
  M -. optional .-> FA[Medicingivning_foraarsaget_af]
